##############################################################################
## This file is part of 'LCLS2 Common Carrier Core'.
## It is subject to the license terms in the LICENSE.txt file found in the
## top-level directory of this distribution and at:
##    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
## No part of 'LCLS2 Common Carrier Core', including this file,
## may be copied, modified, propagated, or distributed except according to
## the terms contained in the LICENSE.txt file.
##############################################################################

include: AmcGenericAdcDacCore.yaml
include: DaqMuxV2.yaml
include: DacSigGeneration.yaml
include: SysGen.yaml
include: TimingProc.yaml

Device: &ApplicationCore
  name: ApplicationCore
  description: Application Core
  size: 0x80000000
  ########
  MMIODev:
  ########
    - <<: *AmcGenericAdcDacCore
      offset: 0x00000000
      stride: 0x00800000
      nelms: 2
    ##################################################
    - <<: *DaqMuxV2
      offset: 0x01000000
      nelms: 2
      stride: 0x01000000
    ##################################################
    - <<: *DacSigGeneration
      offset: 0x03000000
      nelms: 2
      stride: 0x01000000
    ##################################################
    - <<: *SysGen
      offset: 0x05000000
      nelms: 2
      stride: 0x01000000
    ##################################################
    - <<: *TimingProc
      offset: 0x07000000
      nelms: 2
      stride: 0x01000000
    #################################################

  #########
  Commands:
  #########
    ##################################################
    # Add your top level commands here
    ##################################################
